# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PeasantQueen.com
email: danielle@peasantqueen.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is for author/artist/librarian Danielle Oakes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.peasantqueen.com"
twitter_username: pqdanielle
github_username:  peasantqueen

# Build settings
plugins:
  - jekyll-feed
collections:
  goals:
    output: true
    permalink: /goals/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - README.md
